---
- hosts: network
  connection: network_cli
  tasks:
    - name: gather facts for ios platforms
      ios_facts:
        gather_subset: all

    - name: run show vstack config
      ios_command:
        commands:
          - show vstack config
      register: showvstack
      ignore_errors: yes

    - name: output facts to terminal window
      debug:
        msg: >
          Device {{ansible_net_hostname}}, model {{ansible_net_model}}, running {{ansible_net_version}},
          {{showvstack}}
