---
- hosts: network
  connection: network_cli
  tasks:
    - name: gather facts for ios platforms
      ios_facts:
        gather_subset: all

    - name: output facts to terminal window
      debug:
        msg: >
          Device {{ansible_net_hostname}}, model {{ansible_net_model}}, running {{ansible_net_version}}

    ## We will ignore errors, because on some IOS platforms this command does not exist and will error out
    - name: run show vstack config
      ios_command:
        commands:
          - show vstack config
      register: showvstack
      ignore_errors: yes

    - name: Check to make if this errors, it is because vstack doesn't exist
      assert:
        that:
          - "'Invalid input detected' in showvstack.module_stderr"
        when: showvstack.msg == 'MODULE FAILURE'

    - name: run show vstack config
      ios_command:
        commands:
          - show version
      register: showvstack

    - name: debug This
      debug:
        var: showvstack

    - name: Check to make sure Cisco's Smart Install Client Feature is not enabled (1/2)
      assert:
        that:
          - "'SmartInstall enabled' not in showvstack.module_stdout"
          - "'Role' not in showvstack.module_stdout"
          - "'Client' not in showvstack.module_stdout"

    - name: Check to make sure Cisco's Smart Install Client Feature is not enabled (1/1)
      assert:
        that:
          - "'Oper Mode' not in showvstack.module_stdout"
          - "'Enabled' not in showvstack.module_stdout"
          - "'Role' not in showvstack.module_stdout"
          - "'Client' not in showvstack.module_stdout"
