---
- hosts: network
  connection: network_cli
  tasks:
    - name: gather facts for ios platforms
      ios_facts:
        gather_subset: all

    - name: output facts to terminal window
      debug:
        msg: The device {{ansible_net_hostname}} is model {{ansible_net_model}} running {{ansible_net_version}}
